/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.3
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// Logger logs errors that occur during the request flow.
type Logger interface {
	Error(args ...interface{})
}

// NoopLogger implements Logger.
type NoopLogger struct{}

func (n *NoopLogger) Error(args ...interface{}) {}

var apiLog Logger = &NoopLogger{}

// SetLog sets the logger of the package.
func SetLog(l Logger) {
	apiLog = l
}
